apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  SPRING_CONFIG_IMPORT_URL: http://config-server:8888
  SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092