spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT_URL:http://localhost:8888}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

